### PR TITLE
Translations Compiled

### PR DESCRIPTION
**Pull request by joninmoz**
All translations compiled

### CODE REVIEW

**Review by chrishappy — COMMENTED** [review]
Looks good to me. 

@viethung7899, could you review it a well?

**Review by viethung7899 — APPROVED** [review]
The translation looks good to me 👍 . 

However, not related to the PR, can you add the `env.example` back? It's the guide to setting up the environment variable?

**Review by viethung7899 — APPROVED** [review]
Translation works 👍

**Comment by chrishappy** [comment]
Merging on behalf of @joninmoz, @TheDavidJorge and @Kheyssper's hard work.

**Pull request merged**
